# Generated by Django 5.2.11 on 2026-03-23 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='frequency',
            field=models.CharField(default='daily', help_text='instant, daily, weekly', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Identifiant universel unique exposé à l'extérieur.", unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Désactivation logique — les données ne sont pas supprimées.', verbose_name='Actif')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='jobs.candidateprofile')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_candidates', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Offre sauvegardee',
                'verbose_name_plural': 'Offres sauvegardees',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('candidate', 'job_offer')},
            },
        ),
    ]
