# Generated by Django 6.0.2 on 2026-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_interviewsession_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_minutes_per_assistant', models.FloatField(default=1.0, help_text='Default minutes allowed per assistant call.')),
                ('end_call_message', models.TextField(default='Your free version is over. Please contact admin to add more minutes.', help_text='Message spoken before the call ends due to time limit.')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
